name: US_FSRCNN
distortion: sr
scale: 4
gpu_ids: [0]
job_dir: exp


network_G:
  which_model_G: fsrcnn
  in_nc: 3
  out_nc: 3
  upscale: 4
  nf: 56
  s: 12
  m: 4
  width_list: [0, 16, 36, 56]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: /media/DATA2/SR/DIV2K/TMP/DIV2K_scale_sub/GT
    dataroot_LQ: /media/DATA2/SR/DIV2K/TMP/DIV2K_scale_sub/LR
    use_shuffle: true
    n_workers: 4
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB



  val_patch:
    name: DIV2K_valid_sub
    mode: LQGT
    dataroot_GT: /media/DATA2/SR/DIV2K/TMP/DIV2K_valid_HR_sub/GT
    dataroot_LQ: /media/DATA2/SR/DIV2K/TMP/DIV2K_valid_HR_sub/LR

  test_1:
    name: test2k
    mode: LQGT
    dataroot_GT: /media/DATA2/SR/Test2K4K8K/test2k/HR/X4
    dataroot_LQ: /media/DATA2/SR/Test2K4K8K/test2k/LR/X4
  test_2:
    name: test4k
    mode: LQGT
    dataroot_GT: /media/DATA2/SR/Test2K4K8K/test4k/HR/X4
    dataroot_LQ: /media/DATA2/SR/Test2K4K8K/test4k/LR/X4
  test_3:
    name: test8k
    mode: LQGT
    dataroot_GT: /media/DATA2/SR/Test2K4K8K/test8k/HR/X4
    dataroot_LQ: /media/DATA2/SR/Test2K4K8K/test8k/LR/X4


path:
  pretrain_model_G: ~
  resume_state: ~

train:
  lr_G: !!float 1e-3
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 2000000
  warmup_iter: -1  # no warm up
  T_period: [2000000]
  restarts: [2000000]
  restart_weights: [1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  lap_w: 0.

  manual_seed: 2000
  val_freq: 3000000

logger:
  print_freq: 10000
  save_checkpoint_freq: !!float 10000

is_train: True
is_test: False

test_mode: image
patch_size: 32
step: 28
add_mask: True


